config/routes.rb
Rails.application.routes.draw do
  get '/admins/sign_up', to: 'welcome#index'
  devise_for :admins
  resources :cathegories
  devise_for :users
  resources :products
  root 'welcome#index'
  get '/welcome', to: 'welcome#index'
  get '/addcart/:id', to: 'command#add_to_cart', as: 'addcart'
  get '/cart', to: 'command#cart', as: 'cart'
  get '/paycart', to: 'command#pay_cart', as: 'pay_cart'
  post '/createpayment', to: 'command#createpayment'
  post '/executepayment', to: 'command#executepayment'
  get '/userpanel', to: 'user_panel#index', as: 'user_panel'
  get '/commandetails/:id', to: 'user_panel#command_details', as: 'command_details'
  get '/adminpanel', to: 'admin_panel#index', as: 'admin_panel'
  get '/paymentcompleted', to: 'command#payment_completed'
  delete '/removeitem/:id', to:'command#remove_item', as: 'remove_item'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cathegory.rb
class Cathegory < ApplicationRecord
  has_many :products
end

app/controllers/cathegories_controller.rb
class CathegoriesController < ApplicationController
  before_action :set_cathegory, only: [:show, :edit, :update, :destroy]
  before_action :check_is_admin, only: [:new, :edit, :create, :update, :destroy]

  # GET /cathegories
  # GET /cathegories.json
  def index
    @cathegories = Cathegory.all
  end

  # GET /cathegories/1
  # GET /cathegories/1.json
  def show
    @product_list = @cathegory.products
  end

  # GET /cathegories/new
  def new
    @cathegory = Cathegory.new
  end

  # GET /cathegories/1/edit
  def edit
  end

  # POST /cathegories
  # POST /cathegories.json
  def create
    @cathegory = Cathegory.new(cathegory_params)

    respond_to do |format|
      if @cathegory.save
        format.html { redirect_to @cathegory, notice: 'Cathegory was successfully created.' }
        format.json { render :show, status: :created, location: @cathegory }
      else
        format.html { render :new }
        format.json { render json: @cathegory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cathegories/1
  # PATCH/PUT /cathegories/1.json
  def update
    respond_to do |format|
      if @cathegory.update(cathegory_params)
        format.html { redirect_to @cathegory, notice: 'Cathegory was successfully updated.' }
        format.json { render :show, status: :ok, location: @cathegory }
      else
        format.html { render :edit }
        format.json { render json: @cathegory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cathegories/1
  # DELETE /cathegories/1.json
  def destroy
    @cathegory.destroy
    respond_to do |format|
      format.html { redirect_to cathegories_url, notice: 'Cathegory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def check_is_admin
      unless admin_signed_in?
        redirect_to '/welcome'
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_cathegory
      @cathegory = Cathegory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cathegory_params
      params.require(:cathegory).permit(:name)
    end
end

app/helpers/cathegories_helper.rb
module CathegoriesHelper
end

app/views/cathegories/_form.html.erb
<%= form_with(model: cathegory, local: true) do |form| %>
  <% if cathegory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cathegory.errors.count, "error") %> prohibited this cathegory from being saved:</h2>

      <ul>
      <% cathegory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :cathegory_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cathegories/edit.html.erb
<h1>Editing Cathegory</h1>

<%= render 'form', cathegory: @cathegory %>

<%= link_to 'Show', @cathegory %> |
<%= link_to 'Back', cathegories_path %>

app/views/cathegories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cathegories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cathegories.each do |cathegory| %>
      <tr>
        <td><%= cathegory.name %></td>
        <td><%= link_to 'Show', cathegory %></td>
        <td><%= link_to 'Edit', edit_cathegory_path(cathegory) %></td>
        <td><%= link_to 'Destroy', cathegory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cathegory', new_cathegory_path %>

app/views/cathegories/new.html.erb
<h1>New Cathegory</h1>

<%= render 'form', cathegory: @cathegory %>

<%= link_to 'Back', cathegories_path %>

app/views/cathegories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cathegory.name %>
</p>

<%@product_list.each do |product| %>
  <%= product.name %>

<% end %>

<%= link_to 'Edit', edit_cathegory_path(@cathegory) %> |
<%= link_to 'Back', cathegories_path %>