config/routes.rb
Rails.application.routes.draw do
  get '/admins/sign_up', to: 'welcome#index'
  devise_for :admins
  resources :cathegories
  devise_for :users
  resources :products
  root 'welcome#index'
  get '/welcome', to: 'welcome#index'
  get '/addcart/:id', to: 'command#add_to_cart', as: 'addcart'
  get '/cart', to: 'command#cart', as: 'cart'
  get '/paycart', to: 'command#pay_cart', as: 'pay_cart'
  post '/createpayment', to: 'command#createpayment'
  post '/executepayment', to: 'command#executepayment'
  get '/userpanel', to: 'user_panel#index', as: 'user_panel'
  get '/commandetails/:id', to: 'user_panel#command_details', as: 'command_details'
  get '/adminpanel', to: 'admin_panel#index', as: 'admin_panel'
  get '/paymentcompleted', to: 'command#payment_completed'
  delete '/removeitem/:id', to:'command#remove_item', as: 'remove_item'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin_panel_controller.rb
class AdminPanelController < ApplicationController

  before_action :check_is_admin

  def index
    @cathegories = Cathegory.all
    @products = Product.all
  end

  private
  def check_is_admin
    unless admin_signed_in?
      redirect_to '/welcome'
    end
  end
end

app/helpers/admin_panel_helper.rb
module AdminPanelHelper
end

app/views/admin_panel/index.html.erb
<div class="container">
<h1><%=t('cathegories') %></h1>
<table class="table">
  <thead>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @cathegories.each do |cathegory| %>
    <tr>
      <td><%= cathegory.name %></td>
      <td><%= link_to 'Show', cathegory %></td>
      <td><%= link_to 'Edit', edit_cathegory_path(cathegory) %></td>
      <td><%= link_to 'Destroy', cathegory, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>
  <br>
  <%= link_to 'New Cathegory', new_cathegory_path, :class => 'btn btn-primary' %>
</div>

<div class="container">
<h1><%=t('products') %></h1>
<table class="table">
  <thead>
  <tr>
    <th><%= t('name') %></th>
    <th><%= t('price') %></th>
    <th><%= t('producer') %></th>
    <th><%= t('quantity') %></th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.price %></td>
      <td><%= product.producer %></td>
      <td><%= product.quantity %></td>
      <td><%= link_to 'Show', product %></td>
      <td><%= link_to 'Edit', edit_product_path(product) %></td>
      <td><%= link_to 'Destroy', product, method: :delete, data: {confirm: 'Are you sure?'} %></td>
    </tr>
  <% end %>
  </tbody>
</table>
  <br>
  <%= link_to t('new_product'), new_cathegory_path, :class => 'btn btn-primary' %>
</div>