config/routes.rb
Rails.application.routes.draw do
  get '/admins/sign_up', to: 'welcome#index'
  devise_for :admins
  resources :cathegories
  devise_for :users
  resources :products
  root 'welcome#index'
  get '/welcome', to: 'welcome#index'
  get '/addcart/:id', to: 'command#add_to_cart', as: 'addcart'
  get '/cart', to: 'command#cart', as: 'cart'
  get '/paycart', to: 'command#pay_cart', as: 'pay_cart'
  post '/createpayment', to: 'command#createpayment'
  post '/executepayment', to: 'command#executepayment'
  get '/userpanel', to: 'user_panel#index', as: 'user_panel'
  get '/commandetails/:id', to: 'user_panel#command_details', as: 'command_details'
  get '/adminpanel', to: 'admin_panel#index', as: 'admin_panel'
  get '/paymentcompleted', to: 'command#payment_completed'
  delete '/removeitem/:id', to:'command#remove_item', as: 'remove_item'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :descriptions
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :check_is_admin, only: [:new, :edit, :create, :update, :destroy]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
    if params[:cathegory]
      @products = Product.where(cathegory_id: params[:cathegory]).find_each
    end
    if params[:query]
      @products = Product.where("name like ? OR producer like ?", "%#{params[:query]}%", "%#{params[:query]}%").find_each
    end


  end

  # GET /products/1
  # GET /products/1.json
  def show
    @description
    if params[:locale] == 'es'
      @description = @product.descriptions.find_by(language: 'es').description
    end
    if params[:locale] == 'cat'
      @description = @product.descriptions.find_by(language: 'cat').description
    end
    if params[:locale] == 'en'
      @description = @product.descriptions.find_by(language: 'en').description
    end
    if params[:locale].nil?
     @description = @product.descriptions.find_by(language: 'cat').description
    end
    @cathegory =  Cathegory.find(@product.cathegory_id).name
  end

  # GET /products/new
  def new
    if admin_signed_in?
    @product = Product.new
    @cathegories = Cathegory.all
    else
      redirect_to '/'
    end
  end

  # GET /products/1/edit
  def edit
      @description_es = @product.descriptions.find_by(language: 'es').description

      @description_cat = @product.descriptions.find_by(language: 'cat').description

      @description_en = @product.descriptions.find_by(language: 'en').description

    @cathegory =  Cathegory.find(@product.cathegory_id).name
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    Description.create(product: @product, language: 'es', description: params[:product][:description_es])
    Description.create(product: @product, language: 'cat', description: params[:product][:description_cat])
    Description.create(product: @product, language: 'en', description: params[:product][:description_en])


    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    @product.descriptions.find_by(language: 'es').update(description: params[:product][:description_es])
    @product.descriptions.find_by(language: 'cat').update(description: params[:product][:description_cat])
    @product.descriptions.find_by(language: 'en').update(description: params[:product][:description_en])

    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def check_is_admin
      unless admin_signed_in?
        redirect_to '/welcome'
      end
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :image, :producer, :quantity, :cathegory_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div style="margin-bottom: 10%" class="container register">
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %><br>
    <%= form.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= form.label :price %><br>
    <%= form.text_field :price, id: :product_price %>
  </div>

  <div class="field">
    <%= form.label :image %><br>
    <%= form.text_field :image, id: :product_image %>
  </div>

  <div class="field">
    <%= form.label :producer %><br>
    <%= form.text_field :producer, id: :product_producer %>
  </div>

  <div class="field">
    <%= form.label :quantity %><br>
    <%= form.number_field :cathegories, id: :product_quantity %>
  </div>

  <div class="field">
    <%= form.label t('description')+' Español' %><br>
    <%= form.text_area 'description_es', id: :description_es ,:value => @description_es, cols: "50", rows: "5" %>
  </div>
  <div class="field">
    <%= form.label t('description')+' Catala' %><br>
    <%= form.text_area 'description_cat', id: :description_cat ,:value => @description_cat,cols: "50", rows: "5"  %>
  </div>
  <div class="field">
    <%= form.label t('description')+' English' %><br>
    <%= form.text_area 'description_en', id: :description_en ,:value => @description_en,cols: "50", rows: "5"  %>
  </div>
  <div class="field">
    <%=form.label t('category') %> <br>
   <%= form.collection_select :cathegory_id, Cathegory.all, :id, :name %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<div id="container" class="row">
  <!--<h1><#%= t('products') %></h1>-->
  <div class="col-lg-3">
    <h1 class="my-4"></h1>
    <div class="list-group">
      <a href="/products?cathegory=1" class="list-group-item"><%= t("Rossa")%></a>
      <a href="/products?cathegory=2" class="list-group-item"><%= t("Roja")%></a>
      <a href="/products?cathegory=3" class="list-group-item"><%= t("Negra")%></a>
    </div>
  </div>

  <div class="row col-lg-9">
      <%@products.each do |product| %>
      <tr>
        <div class="col-lg-4 col-md-6 mb-4">
          <div class="card h-100">
            <a href="#"><img class="card-img-top" src=<%=product.image%> alt=""></a>
            <div class="card-body">
              <h4 class="card-title">
                <%= link_to product.name, product_path(product.id ,:locale => I18n.locale) %>
              </h4>
              <% if user_signed_in? %>
                <%= link_to t('addcart'), addcart_path(product.id, :locale => I18n.locale)%>
              <% end %>
              <h5><%= product.price%> €</h5>
            </div>
            <div class="card-footer">
              <p class="text-muted"><%=product.producer%></p>
            </div>
          </div>
        </div>
      </tr>
      <% end %>
  </div>
  <br>


</div>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div id="product" class="row">
  <div class="col-lg-6">
    <img src="<%=@product.image %>" alt="Could not load the image">
  </div>
<div class="col-lg-6">
<p id="notice"><%= notice %></p>

<p>
  <strong><%=t('name')%>:</strong>
  <%= @product.name %>
</p>

<p>
  <strong><%=t('price')%>:</strong>
  <%= @product.price %> €
</p>

<p>
  <strong><%=t('producer')%>:</strong>
  <%= @product.producer %>
</p>

<p>
  <strong><%=t('description')%>:</strong>
  <%= @description %>
</p>
<p>
  <strong><%=t('category') %>:</strong>
  <%= t(@cathegory) %>
</p>
  <% if user_signed_in? %>
    <%= link_to t('addcart'), addcart_path(@product.id) %>
  <% end %>
<% if admin_signed_in? %>
  <%= link_to 'Edit', edit_product_path(@product) %> |
  <%= link_to 'Back', products_path %>
<% end %>
</div>
</div>