config/routes.rb
Rails.application.routes.draw do
  get '/admins/sign_up', to: 'welcome#index'
  devise_for :admins
  resources :cathegories
  devise_for :users
  resources :products
  root 'welcome#index'
  get '/welcome', to: 'welcome#index'
  get '/addcart/:id', to: 'command#add_to_cart', as: 'addcart'
  get '/cart', to: 'command#cart', as: 'cart'
  get '/paycart', to: 'command#pay_cart', as: 'pay_cart'
  post '/createpayment', to: 'command#createpayment'
  post '/executepayment', to: 'command#executepayment'
  get '/userpanel', to: 'user_panel#index', as: 'user_panel'
  get '/commandetails/:id', to: 'user_panel#command_details', as: 'command_details'
  get '/adminpanel', to: 'admin_panel#index', as: 'admin_panel'
  get '/paymentcompleted', to: 'command#payment_completed'
  delete '/removeitem/:id', to:'command#remove_item', as: 'remove_item'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Beercat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>BeerCat</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/css/bootstrap-select.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Latest compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.12.4/js/bootstrap-select.min.js"></script>
  </head>

  <body>
  <div class="main-content">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a href="/welcome"><img class="navbar-brand-logo" src="https://i.imgur.com/FMMdKxT.png" alt=""></a>
      <a class="navbar-brand" href="/welcome?locale=<%=I18n.locale%>">BeerCat</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">

          <li class="nav-item">
            <%= link_to t('catalog'), products_path, {:class => 'btn btn-success'} %>
          </li>

          <li class="nav-item">
            <form action="/products?locale=<%=I18n.locale%>" method="get">
              <input type="text" name="query">
              <input type="submit" value=<%= t('buscar') %>>
            </form>
          </li>
          <li class="nav-item">
            <% if user_signed_in? %>
              <a class="nav-link"><%=t('welcome') %> <%= @user_name %></a>
            <% else %>
              <%= link_to t('sign_in'), user_session_path(:locale => I18n.locale), {:class => 'nav-link'} %>
            <% end %>
          </li>
          <li class="nav-item">
            <% unless user_signed_in? %>
              <%= link_to t('register'), new_user_registration_path(:locale => I18n.locale), {:class => 'nav-link'} %>
            <% end %>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to t('user_panel'), user_panel_path(:locale => I18n.locale), method: :get, :class => 'btn btn-secondary' %>
            </li>
          <% end %>
          <% if admin_signed_in? %>
            <li class="nav-item">
              <%= link_to t('admin_panel'), admin_panel_path(:locale => I18n.locale), method: :get, :class => 'btn btn-secondary' %>
            </li>
          <% end %>
          <% if user_signed_in? %>
            <li class="nav-item">
              <a href="/cart?locale=<%=I18n.locale%>" class="btn btn-secondary">
                <i class="fa fa-shopping-cart" style="font-size:20px"></i> (<%= @num_commands %>)
              </a>
            </li>
          <% end %>
          <li class="nav-item">
            <% if admin_signed_in? %>
              <%= link_to('Logout admin', destroy_admin_session_path(:locale => I18n.locale), method: :delete, :class => 'nav-link') %>
            <% elsif user_signed_in? %>
              <%= link_to('Logout', destroy_user_session_path(:locale => I18n.locale), method: :delete, :class => 'btn btn-secondary') %>
            <% end %>
          </li>
        </ul>
      </div>

    </div>
      <div style="float : right" class="dropdown">
        <button class="btn btn-secondary dropdown-toggle">Idioma <i class=""></i></button>
        <div class="dropdown-content">
          <%= link_to 'Catala', {:locale => 'cat'} %>
          <%= link_to 'Español', {:locale => 'es'} %>
          <%= link_to 'English', {:locale => 'en'} %>
        </div>
      </div>
  </nav>




    <%= yield %>
<div id="ant-foot"></div>
  <div id="foot" class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Your Website 2017</p>
    </div>
    <!-- /.container -->
  </div>
  </div>
  </body>
</html>